<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\AdminMenu;
use Carbon\Carbon;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing menus
        AdminMenu::truncate();

        $now = Carbon::now();

        $menus = [
            // ROOT GROUPS
            [
                'id' => 'group_dashboard',
                'name' => 'sys.nav.dashboard',
                'code' => 'dashboard',
                'parent_id' => null,
                'type' => 'GROUP',
                'icon' => null,
                'path' => null,
                'component' => null,
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'group_academics',
                'name' => 'sys.nav.academics',
                'code' => 'academics',
                'parent_id' => null,
                'type' => 'GROUP',
                'icon' => null,
                'path' => null,
                'component' => null,
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'group_management',
                'name' => 'sys.nav.management',
                'code' => 'management',
                'parent_id' => null,
                'type' => 'GROUP',
                'icon' => null,
                'path' => null,
                'component' => null,
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'group_reports',
                'name' => 'sys.nav.reports',
                'code' => 'reports',
                'parent_id' => null,
                'type' => 'GROUP',
                'icon' => null,
                'path' => null,
                'component' => null,
                'meta' => null,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // DASHBOARD GROUP ITEMS
            [
                'id' => 'school_overview',
                'name' => 'sys.nav.school_overview',
                'code' => 'school_overview',
                'parent_id' => 'group_dashboard',
                'type' => 'MENU',
                'icon' => 'local:ic-analysis',
                'path' => '/school-overview',
                'component' => '/pages/dashboard/school-overview',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // ACADEMICS GROUP ITEMS
            [
                'id' => 'students',
                'name' => 'sys.nav.students',
                'code' => 'students',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:student-bold',
                'path' => '/students',
                'component' => null,
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'student_list',
                'name' => 'sys.nav.student_list',
                'code' => 'students:list',
                'parent_id' => 'students',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/students/list',
                'component' => '/pages/students/list',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'student_admission',
                'name' => 'sys.nav.student_admission',
                'code' => 'students:admission',
                'parent_id' => 'students',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/students/admission',
                'component' => '/pages/students/admission',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'student_promotion',
                'name' => 'sys.nav.student_promotion',
                'code' => 'students:promotion',
                'parent_id' => 'students',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/students/promotion',
                'component' => '/pages/students/promotion',
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'teachers',
                'name' => 'sys.nav.teachers',
                'code' => 'teachers',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:chalkboard-teacher-bold',
                'path' => '/teachers',
                'component' => null,
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'teacher_list',
                'name' => 'sys.nav.teacher_list',
                'code' => 'teachers:list',
                'parent_id' => 'teachers',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/teachers/list',
                'component' => '/pages/teachers/list',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'teacher_profile',
                'name' => 'sys.nav.teacher_profile',
                'code' => 'teachers:profile',
                'parent_id' => 'teachers',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/teachers/profile',
                'component' => '/pages/teachers/profile',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'classes',
                'name' => 'sys.nav.classes',
                'code' => 'classes',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:graduation-cap-bold',
                'path' => '/classes',
                'component' => null,
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'class_list',
                'name' => 'sys.nav.class_list',
                'code' => 'classes:list',
                'parent_id' => 'classes',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/classes/list',
                'component' => '/pages/classes/list',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'timetable',
                'name' => 'sys.nav.timetable',
                'code' => 'timetable',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:calendar-blank-bold',
                'path' => '/timetable',
                'component' => null,
                'meta' => null,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'timetable_weekly',
                'name' => 'sys.nav.timetable_weekly',
                'code' => 'timetable:weekly',
                'parent_id' => 'timetable',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/timetable/weekly',
                'component' => '/pages/timetable/weekly',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'attendance',
                'name' => 'sys.nav.attendance',
                'code' => 'attendance',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:calendar-check-bold',
                'path' => '/attendance',
                'component' => null,
                'meta' => null,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'mark_attendance',
                'name' => 'sys.nav.mark_attendance',
                'code' => 'attendance:mark',
                'parent_id' => 'attendance',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/attendance/mark',
                'component' => '/pages/attendance/mark',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'attendance_report',
                'name' => 'sys.nav.attendance_report',
                'code' => 'attendance:report',
                'parent_id' => 'attendance',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/attendance/report',
                'component' => '/pages/attendance/report',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'exams',
                'name' => 'sys.nav.exams',
                'code' => 'exams',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:exam-bold',
                'path' => '/exams',
                'component' => null,
                'meta' => null,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'exam_management',
                'name' => 'sys.nav.exam_management',
                'code' => 'exams:management',
                'parent_id' => 'exams',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/exams/management',
                'component' => '/pages/exams/management',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'exam_results',
                'name' => 'sys.nav.exam_results',
                'code' => 'exams:results',
                'parent_id' => 'exams',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/exams/results',
                'component' => '/pages/exams/results',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'assignments',
                'name' => 'sys.nav.assignments',
                'code' => 'assignments',
                'parent_id' => 'group_academics',
                'type' => 'CATALOGUE',
                'icon' => 'ph:notebook-bold',
                'path' => '/assignments',
                'component' => null,
                'meta' => null,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'assignment_list',
                'name' => 'sys.nav.assignment_list',
                'code' => 'assignments:list',
                'parent_id' => 'assignments',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/assignments/list',
                'component' => '/pages/assignments/list',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'assignment_create',
                'name' => 'sys.nav.assignment_create',
                'code' => 'assignments:create',
                'parent_id' => 'assignments',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/assignments/create',
                'component' => '/pages/assignments/create',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // MANAGEMENT GROUP ITEMS
            [
                'id' => 'fees',
                'name' => 'sys.nav.fees',
                'code' => 'fees',
                'parent_id' => 'group_management',
                'type' => 'CATALOGUE',
                'icon' => 'ph:currency-dollar-bold',
                'path' => '/fees',
                'component' => null,
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'fee_structure',
                'name' => 'sys.nav.fee_structure',
                'code' => 'fees:structure',
                'parent_id' => 'fees',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/fees/structure',
                'component' => '/pages/fees/structure',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'fee_collection',
                'name' => 'sys.nav.fee_collection',
                'code' => 'fees:collection',
                'parent_id' => 'fees',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/fees/collection',
                'component' => '/pages/fees/collection',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'fee_reports',
                'name' => 'sys.nav.fee_reports',
                'code' => 'fees:reports',
                'parent_id' => 'fees',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/fees/reports',
                'component' => '/pages/fees/reports',
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'gallery',
                'name' => 'sys.nav.gallery',
                'code' => 'gallery',
                'parent_id' => 'group_management',
                'type' => 'CATALOGUE',
                'icon' => 'ph:image-bold',
                'path' => '/gallery',
                'component' => null,
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'photo_gallery',
                'name' => 'sys.nav.photo_gallery',
                'code' => 'gallery:photos',
                'parent_id' => 'gallery',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/gallery/photos',
                'component' => '/pages/gallery/photos',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'video_gallery',
                'name' => 'sys.nav.video_gallery',
                'code' => 'gallery:videos',
                'parent_id' => 'gallery',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/gallery/videos',
                'component' => '/pages/gallery/videos',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // Camera Management System
            [
                'id' => 'cameras',
                'name' => 'sys.nav.cameras',
                'code' => 'cameras',
                'parent_id' => 'group_management',
                'type' => 'CATALOGUE',
                'icon' => 'ph:camera-bold',
                'path' => '/cameras',
                'component' => null,
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'camera_management',
                'name' => 'sys.nav.camera_management',
                'code' => 'cameras:management',
                'parent_id' => 'cameras',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/cameras/management',
                'component' => '/pages/cameras/CameraManagement',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'camera_permissions',
                'name' => 'sys.nav.camera_permissions',
                'code' => 'cameras:permissions',
                'parent_id' => 'cameras',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/cameras/permissions',
                'component' => '/pages/cameras/CameraPermissions',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'camera_analytics',
                'name' => 'sys.nav.camera_analytics',
                'code' => 'cameras:analytics',
                'parent_id' => 'cameras',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/cameras/analytics',
                'component' => '/pages/cameras/CameraAnalytics',
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            [
                'id' => 'system',
                'name' => 'sys.nav.system.index',
                'code' => 'system',
                'parent_id' => 'group_management',
                'type' => 'CATALOGUE',
                'icon' => 'local:ic-management',
                'path' => '/system',
                'component' => null,
                'meta' => null,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'system_user',
                'name' => 'sys.nav.system.user',
                'code' => 'system:user',
                'parent_id' => 'system',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/system/user',
                'component' => '/pages/management/system/user',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'system_role',
                'name' => 'sys.nav.system.role',
                'code' => 'system:role',
                'parent_id' => 'system',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/system/role',
                'component' => '/pages/management/system/role',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'system_permission',
                'name' => 'sys.nav.system.permission',
                'code' => 'system:permission',
                'parent_id' => 'system',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/system/permission',
                'component' => '/pages/management/system/permission',
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],

            // REPORTS GROUP ITEMS
            [
                'id' => 'reports',
                'name' => 'sys.nav.reports',
                'code' => 'reports',
                'parent_id' => 'group_reports',
                'type' => 'CATALOGUE',
                'icon' => 'ph:chart-bar-bold',
                'path' => '/reports',
                'component' => null,
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'reports_analytics',
                'name' => 'sys.nav.reports_analytics',
                'code' => 'reports:analytics',
                'parent_id' => 'reports',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/reports/analytics',
                'component' => '/pages/reports/analytics',
                'meta' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'student_reports',
                'name' => 'sys.nav.student_reports',
                'code' => 'reports:students',
                'parent_id' => 'reports',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/reports/students',
                'component' => '/pages/reports/students',
                'meta' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'id' => 'financial_reports',
                'name' => 'sys.nav.financial_reports',
                'code' => 'reports:financial',
                'parent_id' => 'reports',
                'type' => 'MENU',
                'icon' => null,
                'path' => '/reports/financial',
                'component' => '/pages/reports/financial',
                'meta' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
        ];

        // Insert all menus in bulk
        AdminMenu::insert($menus);

        $this->command->info('Admin menus seeded successfully!');
    }
}
